# Generated by Django 4.2.5 on 2023-09-30 18:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='client',
            name='position',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(null=True, upload_to=app.models.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
