# Generated by Django 4.2.5 on 2023-09-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_button_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='logo',
            field=models.ImageField(null=True, upload_to='app/media/logo/'),
        ),
        migrations.AddField(
            model_name='button',
            name='logo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
