# Generated by Django 4.2.5 on 2023-09-30 19:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_button_logo_button_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='app/media/logo/', validators=[app.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='button',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
